# Generated by Django 5.2.3 on 2025-07-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
